// <auto-generated />
namespace BookCollectionWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BookCollection_manytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookCollection_manytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201809292048589_BookCollection_manytomany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
